version: '1.0'
services: 
  phylobook_pipeline:
    container_name: phylobook_pipeline
    build: .
    platform: linux/amd64

    volumes:
      - .:/phylobook_pipeline
    
    # If you are on linux and you would like the output file not to be owned by root
    # Change this to be your userid:groupid, which can be obtained with the id command
    # user: userid:groupid

    tty: true
